import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";

//#448c7e;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Navbar />
      </main>

      <footer></footer>
    </div>
  );
}
